### ISSUE TITLE
AX PBL Week 2

### ISSUE THREAD

**Issue by purplebears321** [zenxha/musicgacha#28]
## Score: 3.75/4.5
[Crossover Graded Ticket](https://github.com/HexaDrakon/why-am-i-here/issues/6)
- [x] MCQ live results = [30/40](https://files.catbox.moe/fh37kc.png)
- [x] FRQ wasn't for PBL, instead worked on [prototype rarity system](https://github.com/zenxha/musicgacha/blob/815bff116f280a1e4057a12d8bfd7b1bbe7a554c/src/main/java/com/musicgacha/controllers/RandomController.java#L22-L32)
- [x] [Ticket](https://github.com/zenxha/musicgacha/issues/28), [GH Pages with Corrections](https://zenxha.github.io/musicgacha/axcorrections)

**Comment by HexaDrakon** [comment]
Total score: 3.75/4.5

MC (1/1): Wow, you did it. Nice work. I'm pretty sure 30 is more than 20, so you get full score here.
PBL (0.5/1): Interesting code. I'm not sure if this is how I would have implemented it -- the `Collections` class has a better way of adding multiple items, although I totally understand wanting to avoid unnecessary imports. Anyway, I subtracted half a point because this system really isn't that much (11 lines of code) and there is no way for me to verify that it works (a REPL would have been nice). I see where you're going with this code, though.
Ticket and Corrections (1/1): Yep, that's a ticket. The corrections are a bit simplistic, but they do the job well and you clearly know why you got every question wrong. Would be nice if you wrote more, but it's not necessary at all. Overall, good work.

Participation (1/1): You were in class every day. You participated, I think. Congrats on participating. I don't know what else to say. Pleasure to have in class?

Quality of Work (0.25/0.5): This seems like mostly quality work to me. I already talked about how short your PBL was, so minus points there.
